#!/usr/bin/env bash
# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Allow HTTP traffic through UFW
sudo ufw allow 'Nginx HTTP'

# Create a basic HTML file
echo "Hello, World!" | sudo tee /var/www/html/index.html

# Start Nginx
sudo systemctl start nginx

# Enable Nginx to start on boot
sudo systemctl enable nginx
