#!/usr/bin/env bash
# Install Nginx web server
sudo apt-get update
sudo apt-get -y install nginx
# Configure /redirect_me to redirect to another page
sudo sed -i 's@root /var/www/html;@root /var/www/html;\n\trewrite ^/redirect_me https://www.holbertonschool.com permanent;@' /etc/nginx/sites-available/default
# Restart Nginx service
sudo service nginx restart
