#!/usr/bin/env bash#!/bin/bash
# Update package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom HTML page for redirection (you can customize this)
echo "This page has moved permanently. Please visit the new page <a href='https://newwebsite.com'>here</a>." | sudo tee /var/www/html/redirect.html

# Configure Nginx to perform the redirection
nginx_config="server {
    listen 80 default_server;
    server_name _;

    location /redirect_me {
        return 301 https://newwebsite.com$request_uri;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }

    location / {
        root /var/www/html;
        index index.html;
    }
}"

echo -e "$nginx_config" | sudo tee /etc/nginx/sites-available/default

# Create a symbolic link to enable the site configuration
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Test the Nginx configuration
sudo nginx -t

# Restart Nginx to apply changes
sudo service nginx restart
