#!/usr/bin/env bash
# Update package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Set the default index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure a custom 404 page and add a redirect for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
custom_error_config="listen 80 default_server;\n\
                     error_page 404 /404.html;\n\
                     location = /404.html {\n\
                         root /var/www/html;\n\
                         internal;\n\
                     }"
sudo sed -i "s/listen 80 default_server;/$custom_error_config/" /etc/nginx/sites-enabled/default

# Configure a specific endpoint redirect (e.g., redirect /redirect_me)
endpoint_redirect="server_name _;\n\
                   rewrite ^/redirect_me https://www.facebook.com permanent;"
sudo sed -i "s/server_name _;/$endpoint_redirect/" /etc/nginx/sites-enabled/default

# Restart the Nginx server to apply changes
sudo service nginx restart
