#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx
# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
# Configure Nginx to use the custom 404 page
sudo sed -i 's/default_server;/default_server;\n\t\terror_page 404 \/404.html;/' /etc/nginx/sites-available/default
# Restart Nginx
sudo service nginx restart
