#!/usr/bin/env bash
# Update system and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Configure firewall for Nginx
sudo ufw allow 'Nginx HTTP'

# Set up web directory and permissions
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www

# Create index page and custom 404 page
echo 'Hello World!' | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx settings
nginx_config="/etc/nginx/sites-enabled/default"

# Add custom header and redirect for /redirect_me
custom_header="add_header X-Served-By \$hostname;"
redirect_config="rewrite ^/redirect_me https://www.blog.ehoneahobed.com permanent;"

# Replace server_name and add custom header
sudo sed -i "s/server_name _;/$custom_header\n\t$redirect_config/" "$nginx_config"

# Configure 404 error page and its location
error_page_config="listen 80 default_server;\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$error_page_config/" "$nginx_config"

# Restart Nginx to apply changes
sudo service nginx restart
