#!/bin/env bash

# Update package repository and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend main
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOF

# Ensure HAProxy can be managed via init script
sudo systemctl enable haproxy
sudo systemctl restart haproxy

# Update hosts file to include server hostnames
echo "127.0.0.1 [STUDENT_ID]-web-01 [STUDENT_ID]-web-02" | sudo tee -a /etc/hosts

# Restart networking service to apply hostname changes
sudo systemctl restart networking
