#!/bin/bash
#!/bin/bash



echo "Star Wars Episode IV: A New Hope"

echo "Scene 1: Tatooine"

echo " "

echo "FADE IN:"

echo " "

echo "EXT. TATOOINE DESERT - DAY"

echo " "

echo "LUKE SKYWALKER is working on his landspeeder."

echo "OBI-WAN KENOBI approaches him."

echo " "

echo "OBI-WAN KENOBI:

Hello there."

echo " "

echo "LUKE SKYWALKER:

How did you get here? I need your help!"

echo " "

echo "OBI-WAN KENOBI:

I have been waiting for you, Luke. I am here to help you become a Jedi Knight."

echo " "

echo "LUKE SKYWALKER:

A Jedi Knight? What's that?"

echo " "

echo "OBI-WAN KENOBI:

It is a path to knowledge and power. But, we must leave Tatooine if you are to become a Jedi."

echo " "

echo "LUKE SKYWALKER:

Okay, I'll go with you."

echo " "

echo "OBI-WAN KENOBI:

Good. We must leave now."

echo " "

echo "FADE OUT."

echo " "

echo "End of Scene 1."

echo " "

echo "The adventure continues in the next scene..."


