#!/usr/bin/env bash
# Bash script that:
# Creates the file /var/run/myscript.pid containing its PID

# Function to handle termination signals
cleanup() {
    echo "Terminating the script..."
    rm -f /var/run/myscript.pid
    exit
}

# Register the cleanup function to handle SIGQUIT and SIGTERM signals
trap cleanup SIGQUIT SIGTERM

# Function to handle SIGINT signal
handle_sigint() {
    echo "Y U no love me?!"
}

# Register the handle_sigint function to handle SIGINT signal
trap handle_sigint SIGINT

# Create the file /var/run/myscript.pid containing its PID
echo $$ > /var/run/myscript.pid

# Infinite loop to display "To infinity and beyond"
while true; do
    echo "To infinity and beyond"
    sleep 2
done
