#!/usr/bin/env bash
# A Bash script that displays Best School ten times, display Best School on 9th iteration, and then Hi on new line using while loop, if statement included

i=1

while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    ((i++))
done
