#!/usr/bin/env bash
# A Bash script that loops through 1 to 10, display bad luck for 4th loop, good luck on the 8th loop, Best School for other iterations

i=1

while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
