#!/usr/bin/env bash
# Script that configures ufw so that it blocks allincoming traffic
#except for TCP ports 22, 443 and 80.

apt-get install ufw -y

ufw default deny incoming
ufw default allow outgoing

ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp

ufw enable
